version: "3.8"

services:
  app:
    container_name: tx_app
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "6060:6060"
      - "4000:8000"
    depends_on:
      - postgesql
      - prometheus
      - node_exporter
      - grafana
    restart: always
    volumes:
      - ./config:/app/config
    networks:
      - tx_network

  postgesql:
    image: postgres:13-alpine
    container_name: tx_postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - tx_network

  prometheus:
    container_name: prometheus_container
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=20d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    networks:
      - tx_network

  node_exporter:
    container_name: node_exporter_container
    image: prom/node-exporter
    ports:
      - '9100:9100'
    networks:
      - tx_network

  grafana:
    container_name: grafana_container
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - tx_network

networks:
  tx_network:
    driver: bridge